server:
  port: 9999

base:
    dir: ${UHOMED_ROUTER_CONFIG_DIR}

spring:
    mvc:
        static-path-pattern: /static/**
    resources:
        static-locations: file:${base.dir}/htdoc/static
    profiles:
      active: ${UHOMED_ROUTER_ACTIVE:dev}


#mybatis:
#  mapper-locations: classpath:config/mybatis/*.xml
#  config-locations: classpath:config/deploy/mybatis-config.xml



logging:
    config: file:${base.dir}/config/${spring.profiles.active}/logback.xml


